use_frameworks!

target 'CoreDataContextManager_Example' do
  platform :ios, '12.0'
  pod 'CoreDataContextManager', :path => '../'

  target 'CoreDataContextManager_Tests' do
    inherit! :search_paths

    pod 'CoreDataContextManager', :path => '../'
    pod 'Specta'
    pod 'Expecta'
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
